// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLySach.Models;

#nullable disable

namespace QuanLySach.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLySach.Models.Sach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Sach", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Phạm Hồng Phước",
                            Price = 150000m,
                            Title = "Lập trình C# cơ bản"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Nguyễn Hoàng Anh",
                            Price = 200000m,
                            Title = "ASP.NET Core Web API"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Trần Minh Đức",
                            Price = 180000m,
                            Title = "Entity Framework Core"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Đỗ Văn Hiếu",
                            Price = 220000m,
                            Title = "SQL Server từ A đến Z"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Võ Minh Tuấn",
                            Price = 120000m,
                            Title = "HTML, CSS, JavaScript"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
